spring.application.name=booking-service

# Placeholder for Local Testing
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=hotel_booking_db

# When you get your Azure string, you will comment out the above
# and uncomment the line below:
# spring.data.mongodb.uri=mongodb://<your-azure-string-here>

# Service URLs (update for production)
hotel.service.url=http://localhost:8081
payment.service.url=http://localhost:8082