spring.application.name=booking-service
server.port=8080

# The clean, standard Atlas connection string
# Replace <password> if it contains special characters like @ (use %40)
#spring.data.mongodb.uri=mongodb+srv://CTSE-DB-USER:CTSE-Y4S1@hotel-booking-system.lskcrrw.mongodb.net/bookings?retryWrites=true&w=majority

#test uri
spring.data.mongodb.uri=mongodb+srv://CTSE-DB-USER:CTSE-Y4S1@hotel-booking-system.lskcrrw.mongodb.net/booking_db?appName=Hotel-Booking-System


# Connection timeouts for external service calls
spring.mvc.async.request-timeout=30000
