spring.application.name=notify-analytics-service
server.port=8084

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://CTSE-DB-USER:CTSE-Y4S1@hotel-booking-system.lskcrrw.mongodb.net/analytics_db?retryWrites=true&w=majority
#spring.data.mongodb.uri=mongodb+srv://admin:adminpassword123@ctse-microservices-clus.4r7fiwl.mongodb.net/analytics_db?retryWrites=true&w=majority
