spring.application.name=payment-service
server.port=8082


# MongoDB connection
spring.data.mongodb.uri=mongodb+srv://CTSE-DB-USER:CTSE-Y4S1@hotel-booking-system.lskcrrw.mongodb.net/payment_db?appName=Hotel-Booking-System


stripe.secret.key=sk_test_51T9L0hDSHvOcTjW8cNGrnwoMtGnkld5xNhe3w98pb6jDHoHWVnv2BLCofNS8Fh0QECTUYNdF5ss1kyqJigdIi4A200iN85jGYt
