spring.application.name=payment-service
server.port=8082


# MongoDB connection
spring.data.mongodb.uri=mongodb+srv://Sachini:sachini01@slholidays.e1cwa.mongodb.net/paymentdb?retryWrites=true&w=majority

stripe.secret.key=sk_test_51T9L0hDSHvOcTjW8cNGrnwoMtGnkld5xNhe3w98pb6jDHoHWVnv2BLCofNS8Fh0QECTUYNdF5ss1kyqJigdIi4A200iN85jGYt
