spring.application.name=payment-service
# PayHere Merchant Secret
payhere.merchant.id=1234399
payhere.merchant.secret=MjA0NzgyMjg1NDIzOTI4MzI0MTQxNjMyMDI5MzgyMzcyMDc5MzM3NA==

# MongoDB connection
spring.data.mongodb.uri=mongodb+srv://Sachini:sachini01@slholidays.e1cwa.mongodb.net/paymentdb?retryWrites=true&w=majority